name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ github.workspace }}
    env:
      HOME: /home/runner
      VCPKG_TOOLCHAIN: /home/runner/vcpkg/scripts/buildsystems/vcpkg.cmake

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clone vcpkg at Boost 1.88 baseline
        run: |
          git clone https://github.com/microsoft/vcpkg.git $HOME/vcpkg
          cd $HOME/vcpkg
          git checkout 48a0cef
          ./bootstrap-vcpkg.sh

      - name: Install Boost 1.88 + gtest
        run: |
          $HOME/vcpkg/vcpkg install \
            boost-system:x64-linux \
            boost-thread:x64-linux \
            boost-json:x64-linux \
            boost-beast:x64-linux \
            boost-redis:x64-linux \
            boost-asio[ssl]:x64-linux \
            gtest:x64-linux \
            --clean-after-build

      - name: Build unit & integration tests
        run: make test

      - name: Run unit & integration tests
        run: make test-run
